# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-06 05:32
from __future__ import unicode_literals

import LonFon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostAndFound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_id', models.CharField(blank=True, max_length=13, null=True, validators=[LonFon.models.validate])),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
