# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-06 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LonFon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostandfound',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='lostandfound',
            name='lost_or_found',
            field=models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], default='Lost', max_length=10),
        ),
    ]
